server:
  port: 8761

spring:
  application:
    name: wakanda-discovery

eureka:
  instance:
    hostname: localhost
  client:
    # Estos dos 'false' son vitales: le dicen que ÉL es el servidor,
    # así que no intente registrarse consigo mismo.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/