global:
  scrape_interval: 5s # Recoger datos cada 5 segundos

scrape_configs:
  - job_name: 'wakanda-services'
    metrics_path: '/actuator/prometheus' # La ruta que Spring Boot expone
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083']