server:
  port: 8888

spring:
  application:
    name: wakanda-config-server
  profiles:
    active: native # Modo local (sin GitHub)
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/ # Busca en la carpeta de abajo