server:
  port: 8082

spring:
  application:
    name: wakanda-emergency

# Configuraci√≥n de Eureka para que el servicio sea localizable
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuraci√≥n personalizada para el sistema de alertas y drones
emergency:
  config:
    umbral-proximidad-drones: 500 # metros
    tiempo-respuesta-objetivo: 300 # segundos
    mensaje-bienvenida: "üö® Sistema de Respuesta a Emergencias de Wakanda Activo"

# Configuraci√≥n del Circuit Breaker para el Gestor de Respuesta
resilience4j:
  circuitbreaker:
    instances:
      emergencyResponse:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s